# Generated by Django 4.1.4 on 2023-01-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaid_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="link_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="token_status",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
