# Generated by Django 4.1.4 on 2023-01-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_ticker", models.CharField(max_length=9)),
                (
                    "number_of_shares",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("stock_name", models.CharField(max_length=255)),
                ("trade_completed", models.BooleanField()),
                ("ticket_closed", models.BooleanField()),
                ("buying", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_api.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=255)),
                ("stock_ticker", models.CharField(max_length=9)),
                (
                    "number_of_shares",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_api.useraccount",
                    ),
                ),
            ],
        ),
    ]
