# Generated by Django 4.1.4 on 2023-01-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockwatch_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traderequest",
            name="buying",
            field=models.BooleanField(default=False),
        ),
    ]
